[www]
user = www-data
group = www-data
listen = 9000

pm = static
pm.max_children = 10

; Логирование медленных запросов (убери когда всё наладится)
slowlog = /var/log/php-fpm-slow.log
request_slowlog_timeout = 2s